version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.2.1

    working_directory: ~/monorepo-builds

    steps:
      - checkout

      - run:
          name: Hash Projects
          command: |
            git log --pretty=format:'%H' -n 1 -- project_a > .project-a-hash.new
            git log --pretty=format:'%H' -n 1 -- project_b > .project-b-hash.new

      - restore_cache:
          keys:
            - v1-project-hashes-{{ .Branch }}
            - v1-project-hashes-master

      - run:
          name: Build modified Projects
          command: |
            if diff .project-a-hash{,.new} > /dev/null; then
              echo "Project A won't be built"
            else
              echo "Building Project A"
            fi

            if diff .project-b-hash{,.new} > /dev/null; then
              echo "Project B won't be built"
            else
              echo "Building Project B"
            fi

      - run:
          name: Test modified Projects
          command: |
            if diff .project-a-hash{,.new} > /dev/null; then
              echo "Project A won't be tested"
            else
              echo "Testing Project A"
            fi

            if diff .project-b-hash{,.new} > /dev/null; then
              echo "Project B won't be tested"
            else
              echo "Testing Project B"
            fi

      - run:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              if diff .project-a-hash{,.new} > /dev/null; then
                echo "Project A won't be deployed"
              else
                echo "Deploying Project A"
              fi

              if diff .project-b-hash{,.new} > /dev/null; then
                echo "Project B won't be deployed"
              else
                echo "Deploying Project B"
              fi
            fi

      - run:
          name: Set new project hashes
          command: |
            mv .project-a-hash{.new,}
            mv .project-b-hash{.new,}

      - save_cache:
          paths:
            - .project-a-hash
            - .project-b-hash
          key: v1-project-hashes-{{ .Branch }}-{{ epoch }}
