version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.2.1
  working_directory: ~/monorepo-builds

jobs:
  clone_and_hash:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-project-hashes-{{ .Branch }}
            - v1-project-hashes-master

      - run:
          name: Copy old hashes to workspace
          command: |
            mkdir -p .project-hashes
            cp .project-a-hash .project-hashes
            cp .project-b-hash .project-hashes

      - run:
          name: Hash Projects
          command: |
            git log --pretty=format:'%H' -n 1 -- project_a > .project-hashes/.project-a-hash.new
            git log --pretty=format:'%H' -n 1 -- project_b > .project-hashes/.project-b-hash.new

      - persist_to_workspace:
          root: .
          paths:
            - .project-hashes

  project_a_changed:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: ls -al
      - run: diff .project-hashes/.project-a-hash{,.new}

  project_b_changed:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: ls -al
      - run: diff .project-hashes/.project-b-hash{,.new}

  save_hashes:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name:
          command: |
            cp .project-hashes/.project-a-hash.new .project-a-hash
            cp .project-hashes/.project-b-hash.new .project-b-hash
      - save_cache:
          key: v1-project-hashes-{{ .Branch }}-{{ epoch }}
          paths:
            - .project-a-hash
            - .project-b-hash

  project_a:
    <<: *defaults
    working_directory: ~/monorepo-builds/project_a
    steps:
      - checkout: ~/monorepo-builds
      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build modified Projects
          command: echo "Building Project A"

      - run:
          name: Test modified Projects
          command: echo "Testing Project A"

      - run:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploying Project A"
            fi

  project_b:
    <<: *defaults
    working_directory: ~/monorepo-builds/project_b
    steps:
      - checkout: ~/monorepo-builds
      - run:
          name: Install dependencies
          command: echo "install"

      - run:
          name: Build modified Projects
          command: echo "Building Project B"

      - run:
          name: Test modified Projects
          command: echo "Testing Project B"

      - run:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploying Project B"
            fi

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - clone_and_hash
      - save_hashes:
          requires:
            - clone_and_hash
      - project_a_changed:
          requires:
            - clone_and_hash
      - project_b_changed:
          requires:
            - clone_and_hash
      - project_a:
          requires:
            - project_a_changed
      - project_b:
          requires:
            - project_b_changed
